### ISSUE TITLE
Link to "Get the AddOn" download is dead

### ISSUE THREAD

**Issue by eliasp** [rugk/googerteller#1]
Clicking on the [Get the AddOn](https://addons.mozilla.org/firefox/addon/googer-teller/?utm_source=github.com&utm_medium=git&utm_content=download-button&utm_campaign=github)-badge shows only:

> If you’ve followed a link from another site for an extension or theme, that item is no longer available. This could be because:
> 
>    The developer removed it. Developers commonly do this because they no longer support the extension or theme, or have replaced it.
>     Mozilla removed it. This can happen when issues are found during the review of the extension or theme, or the extension or theme has been abusing the terms and conditions for addons.mozilla.org. The developer has the opportunity to resolve the issues and make the add-on available again.

**Comment by rugk** [comment]
Likely was not reviewed by then. Now it is.

I just checked and clicked the link and it works.

Please try again and let me know if that should not work.
