### ISSUE TITLE
No icon showing on Firefox 104 (Latest) MacOS 12.5

### ISSUE THREAD

**Issue by replete** [rugk/googerteller#4]
## Bug description

It does not show up in the extension toolbar or the expanded list:

![Screen Shot 2022-08-26 at 12 11 42](https://user-images.githubusercontent.com/812139/186891469-80f08e13-c9bc-49c7-a5d8-0fef3ba4533a.png)

![Screen Shot 2022-08-26 at 12 12 35](https://user-images.githubusercontent.com/812139/186891611-696e7b08-1e42-4ed3-aa3d-d3b4e5d67350.png)

But the extension does work.

## Steps to reproduce
Install the addon on Firefox MacOS, look for icon in toolbar.

### Actual behavior
No icon in toolbar.

### Expected behavior
Icon in toolbar

## System
Operating system and version: MacOS 12.5
Browser and version: Firefox 104.0
Add-on version: 0.1

**Comment by replete** [comment]
Also, this doesn't seem to work at all in Firefox Android, but is probably the same bug

FYI: You can make Addons work in Firefox for Android _Nightly_ + other Privacy forks of FF Android such (e.g. Mull) by:
1) Login to https://addons.mozilla.org on desktop
2) Visit 'View My Collections' (on desktop, top right username dropdown > 'View My Collections'
3) Create a new collection, naming it,
4) Add Google Teller + any other addons you want on android (recommendations: uBlock Origin, Dark Reader, Privacy Redirect)
5) Take note of your collection name and userid, which are both as the last two segments of the URL you are editing your addon collection (looks like: https://addons.mozilla.org/en-US/firefox/collections/9999999/collectionname )
6) On Firefox Android Nightly find the Custom Addons Collection setting and enter the collection name and collection ID collected before.

**Comment by rugk** [comment]
It does not show up, because it has no icon/popup or so. It's configured via the settings and works without all that.

It's not tested for ANdroid (though published), so maybe there is a different bug.


If you want to dig into this could you (or someone else), debug the extension and post the logs while using it here. See:
https://extensionworkshop.com/documentation/develop/developing-extensions-for-firefox-for-android/#debug-your-extension

**Comment by replete** [comment]
Thanks. Definitely wish it had a toolbar icon to disable when it was going making crazy max volume noises!

Probably best to remove 'Compatible with Firefox for Android' from the Features on README.md if it is not supported by Android, it did not produce audio for me

**Comment by replete** [comment]
Closing because it's not a bug its a feature
